### PR TITLE
PR: Add product.html, assests/images and update css.

### LINKED ISSUE #1: [feature] add Product Page
You have to design and develop Product page for out estore.

### PR DESCRIPTION
**Pull request by MazharRehan**
Resolve: #1

### CODE REVIEW

**Review by Faizan0030 — APPROVED** [review]
Good work. Keep it up..!

**Review by Usama-Bin-Naseer — APPROVED** [review]
Good

**Review by ZainBinImran — APPROVED** [review]
Great Work!

**Review by umansheikh0611 — CHANGES_REQUESTED** [review]
Fix Conflicts

**Review by umansheikh0611 — APPROVED** [review]

**Pull request merged**
